import { Product } from "./app/shared/models/product";

export const sample_products: Product[] = [
    {id: 0,
        product_key: "SSH-23029",
        name: "Notebooks",
        description: "Notebooks different colors",
        price_per_dozen: 10,
        price_box: 8,
        pieces_per_box: 10,
        total_pieces: 20,
        tags: "School supplies, books",
        imageUrl: "/assets/products_images/ssh-23029.png"
    },
    {id: 1,
        product_key: "SSH-23V22",
        name: "Hair things",
        description: "Hair things multiple colors, ask for more info",
        price_per_dozen: 6,
        price_box: 8,
        pieces_per_box: 5,
        total_pieces: 20,
        tags: "School supplies, books",
        imageUrl: "/assets/products_images/ssh-23v22.png"
    },
    {id: 2,
        product_key: "SSH-23023",
        name: "Kitsch Satin Hair ",
        description: " Softer Than Silk Scrunchies for Hair",
        price_per_dozen: 10,
        price_box: 5,
        pieces_per_box: 11.98,
        total_pieces: 20,
        tags: " Hair Scrunchies for Women",
        imageUrl: "/assets/products_images/ssh-23023.jpg"
    },
    {id: 3,
        product_key: "SSH-23025",
        name: " Hair Clip Non-Slip Metal Black Hair ",
        description: " Softer Than Silk Scrunchies for Hair",
        price_per_dozen: 13,
        price_box: 5,
        pieces_per_box: 13,
        total_pieces: 10,
        tags: " Metal Black Hair Barrettes",
        imageUrl: "/assets/products_images/ssh-23025.jpg"
    },


    {id: 4,
        product_key: "SSH-23028",
        name: "Mens Digital Watch,   ",
        description: "  Back Light/Alarm/Date/Shockproof",
        price_per_dozen: 20,
        price_box: 50,
        pieces_per_box: 26,
        total_pieces: 30,
        tags: " Hair Clip Non-Slip Metal Black Hair Barrettes",
        imageUrl: "/assets/products_images/ssh-23028.jpg"
    },
    {id: 5,
        product_key: "SSH-23030",
        name: "Formula CV for Dogs & Cats  ",
        description: " By Rx Vitamins for Pets",
        price_per_dozen: 41,
        price_box:100,
        pieces_per_box: 38,
        total_pieces: 30,
        tags: "Supports normal heart and vasculationing ",
        imageUrl: "/assets/products_images/ssh-23030.jpg"
    },
    {id: 6,
        product_key: "SSH-23031",
        name: "Magid® T-REX® Arctic Series® TRX449W  ",
        description: "  Gloves ANSI Cut Level A5",
        price_per_dozen: 25,
        price_box: 50,
        pieces_per_box: 22,
        total_pieces: 60,
        tags: " The Insulcore® Extreme Thermal Lining protects against",
        imageUrl: "/assets/products_images/ssh-23031.jpg"
    },
    {id: 7,
        product_key: "SSH-23032",
        name: " Rattle Toy(Elephant)",
        description: "hanging toys that have fun, sensory interaction",
        price_per_dozen:19,
        price_box: 20,
        pieces_per_box: 18,
        total_pieces: 30,
        tags: " The Insulcore® Extreme Thermal Lining protects against",
        imageUrl: "/assets/products_images/ssh-23032.jpg"
    },
    {id: 8,
        product_key: "SSH-23033",
        name: " Breaking a sweat never felt so good",
        description: ". Our Men's Active Long Sleeve Tech Tee feels ",
        price_per_dozen:19,
        price_box: 20,
        pieces_per_box: 18,
        total_pieces: 30,
        tags: " light and breezy while super-soft",
        imageUrl: "/assets/products_images/ssh-23033.jpg"
    },

    {id: 8,
    product_key: "SSH-23033",
    name: " Breaking a sweat never felt so good",
    description: ". Our Men's Active Long Sleeve Tech Tee feels ",
    price_per_dozen:19,
    price_box: 20,
    pieces_per_box: 18,
    total_pieces: 30,
    tags: " light and breezy while super-soft",
    imageUrl: "/assets/img/bestbuylogo.jpg.jpg"
},


]
